GET http://localhost:5000/api/v1/ItemGroups HTTP/1.1
Api-Key: a1b2c3d4e5

###
GET http://localhost:5000/api/v1/ItemGroups/1 HTTP/1.1
Api-Key: a1b2c3d4e5

###
POST http://localhost:5000/api/v1/ItemGroup HTTP/1.1
Content-Type: application/json
Api-Key: a1b2c3d4e5

{
    "id": 1,
    "name": "Test",
    "description": "Test",
    "created_at": "2000-03-11T13:11:14Z",
    "updated_at": "2000-03-12T16:11:14Z"
}
###
PUT http://localhost:5000/api/v1/ItemGroups/1 HTTP/1.1
Content-Type: application/json
Api-Key: a1b2c3d4e5

{
    "id": 1,
    "name": "TESTEST",
    "description": "Test",
    "created_at": "2000-03-11T13:11:14Z",
    "updated_at": "2000-03-12T16:11:14Z"
}
###
DELETE http://localhost:5000/api/v1/ItemGroup/1 HTTP/1.1
Api-Key: a1b2c3d4e5
