POST http://localhost:5000/api/v1/locations
Content-Type: application/json

{
    "id": 4,
    "warehouseId": 2, 
    "code": "AA.1.0",
    "name": "Row: A, Rack: 1, Shelf: 0",
    "createdAt": "1992-05-15T03:21:32",
    "updatedAt": "1992-05-15T03:21:32"
}
//ik ben bijna zeker ervan dat warehouseid gepakt moet worden van de andere classes moet hier later op terug komen
### Get all locations
GET http://localhost:5000/api/v1/locations
#######
GET http://localhost:5000/api/v1/locations/1
#####
PUT http://localhost:5000/api/v1/locations/1
Content-Type: application/json

{
    "id": 1,
    "warehouseId": 1, 
    "code": "SAMI TEST",
    "name": "Row: A, Rack: 1, Shelf: 1",
    "createdAt": "1992-05-15T03:21:32",
    "updatedAt": "2024-10-19T10:00:00"
    //volgensmij hoort id automatisch te zijn of niet
}
#####
DELETE http://localhost:5000/api/v1/locations/1