GET http://localhost:5000/api/v1/orders
Api-Key: a1b2c3d4e5
###

GET http://localhost:5000/api/v1/orders/1
Api-Key: a1b2c3d4e5
###

POST http://localhost:5000/api/v1/orders
Content-Type: application/json
Api-Key: a1b2c3d4e5

{
    "id": 1,
    "source_Id": 1,
    "order_Date": "2024-10-22T10:00:00",
    "request_Date": "2024-10-23T10:00:00",
    "reference": "ORD1234",
    "reference_Extra": "ORD_EXTRA_001",
    "order_Status": "Pending",
    "notes": "Please process as soon as possible.",
    "shipping_Notes": "Fragile items.",
    "picking_Notes": "Pick items in the correct order.",
    "warehouse_Id": 1,
    "ship_To": 123,
    "bill_To": 456,
    "shipment_Id": 101,
    "total_Amount": 1000.00,
    "total_Discount": 50.00,
    "total_Tax": 50.00,
    "total_Surcharge": 10.00,
    "items": [
        {
            "Uid": "P000001",
            "code": "sjQ23408K",
            "description": "Face-to-face clear-thinking complexity",
            "short_description": "Brief description here",
            "upc_code": "6523540947122",
            "model_number": "63-OFFTq0T",
            "commodity_code": "oTo304",
            "item_line": 11,
            "item_group": 73
        }
    ],
    "created_At": "2024-10-22T10:00:00",
    "updated_At": "2024-10-22T10:00:00"
}
###

GET http://localhost:5000/api/v1/orders/1
Api-Key: a1b2c3d4e5
###

PUT http://localhost:5000/api/v1/orders/1
Content-Type: application/json
Api-Key: a1b2c3d4e5

{
    "id": 1,
    "source_Id": 1,
    "order_Date": "2024-10-22T10:00:00",
    "request_Date": "2024-10-23T10:00:00",
    "reference": "ORD1234",
    "reference_Extra": "ORD_EXTRA_001",
    "order_Status": "Pending",
    "notes": "Edited. New notes for the order.",
    "shipping_Notes": "Fragile items.",
    "picking_Notes": "Pick items in the correct order.",
    "warehouse_Id": 1,
    "ship_To": 123,
    "bill_To": 456,
    "shipment_Id": 101,
    "total_Amount": 1050.00,
    "total_Discount": 60.00,
    "total_Tax": 55.00,
    "total_Surcharge": 12.00,
    "items": [
        {
            "Uid": "P000001",
            "code": "sjQ23408K",
            "description": "Updated description for the item",
            "short_description": "Updated brief description",
            "upc_code": "6523540947122",
            "model_number": "63-OFFTq0T",
            "commodity_code": "oTo304",
            "item_line": 11,
            "item_group": 73
        }
    ],
    "created_At": "2024-10-22T10:00:00",
    "updated_At": "2024-10-22T12:00:00"
}

###
DELETE http://localhost:5000/api/v1/orders/1
Api-Key: a1b2c3d4e5

